### ISSUE TITLE
Incompatible with Architectury API

### ISSUE THREAD

**Issue by xanthian** [Darkhax-Minecraft/Coloured-Tooltips#8]
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyBackgroundColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipBackgroundColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyBackgroundColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipBackgroundColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyBackgroundColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipBackgroundColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyBackgroundColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipBackgroundColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyBackgroundColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipBackgroundColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyBackgroundColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipBackgroundColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyBackgroundColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipBackgroundColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyBackgroundColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipBackgroundColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyBackgroundColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipBackgroundColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyBackgroundColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipBackgroundColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyBackgroundColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipBackgroundColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyStartColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipOutlineGradientTopColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyStartColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipOutlineGradientTopColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyStartColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipOutlineGradientTopColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyStartColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipOutlineGradientTopColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyStartColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipOutlineGradientTopColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyEndColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipOutlineGradientBottomColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyEndColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipOutlineGradientBottomColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyEndColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipOutlineGradientBottomColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyEndColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipOutlineGradientBottomColor(I)I from mod architectury with priority 1000
[21:11:19] [main/WARN]: @ModifyConstant conflict. Skipping colouredtooltips.mixins.json:MixinScreen->@ModifyConstant::modifyEndColor(I)I from mod colouredtooltips with priority 1000, already redirected by architectury.mixins.json:client.MixinScreen->@ModifyConstant::modifyTooltipOutlineGradientBottomColor(I)I from mod architectury with priority 1000
[21:11:19] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_437 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_437 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.17.1-59-FABRIC.jar:?]
	at net.minecraft.class_6396.handler$chf000$patchouli_addContext(class_6396.java:1016) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:275) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.17.1-59-FABRIC.jar:?]
	at net.minecraft.class_6396.handler$chf000$patchouli_addContext(class_6396.java:1016) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:275) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyBackgroundColor(I)I in colouredtooltips.mixins.json:MixinScreen from mod colouredtooltips failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap ColouredTooltips-Fabric-1.17.1-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.17.1-59-FABRIC.jar:?]
	at net.minecraft.class_6396.handler$chf000$patchouli_addContext(class_6396.java:1016) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:275) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]

===
Modlist

	- advanced_runtime_resource_pack 0.4.3 via enhancedblockentities
	- advancedcompass 1.2.6
	- advancementinfo 1.17.1-fabric0.36.1-1.3
	- advancementplaques 1.4.2
	- alternatecurrent 1.1.0
	- appliedenergistics2 9.0.0-beta.2
	- architectury 2.8.66
	- autorun 0.3.0
	- bbor 2.4-1.17.1
	- blur 2.4.0
	- cardinal-components-base 3.0.0 via trinkets
	- cardinal-components-entity 3.0.0 via trinkets
	- cem 0.6.2
	- clear-skies 2.0.89
	- clickthrough 1.17.1-fabric0.36.1-0.4
	- cloth-api 2.0.54
	- cloth-armor-api-v1 1.5.47 via modern_industrialization
	- cloth-basic-math 0.6.0 via cloth-config2
	- cloth-client-events-v0 2.0.54 via cloth-api
	- cloth-common-events-v1 2.0.54 via cloth-api
	- cloth-config2 5.2.47
	- cloth-datagen-api-v1 2.0.54 via cloth-api
	- cloth-scissors-api-v1 2.0.54 via cloth-api
	- cloth-utils-v1 2.0.54 via cloth-api
	- collective-fabric 3.14
	- colouredtooltips 12.0.2
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- compactstatuseffects 2.0.1
	- consistency_plus 0.4.3+1.17
	- continuity 1.0.3+1.17
	- crowdin-translate 1.3+1.17 via clickthrough
	- cullleaves 2.3.2
	- darkness 2.0.87
	- easiervillagertrading 1.17.1-fabric0.36.1-1.5.4
	- eatinganimationid 1.2
	- enhancedblockentities 0.5+1.17
	- entityculling 1.3.3
	- fabric 0.45.0+1.17
	- fabric-api-base 0.4.0+cf39a74318 via fabric
	- fabric-api-lookup-api-v1 1.5.0+e821752d18 via fabric
	- fabric-biome-api-v1 3.2.2+cf39a74318 via fabric
	- fabric-blockrenderlayer-v1 1.1.6+cf39a74318 via fabric
	- fabric-command-api-v1 1.1.4+cf39a74318 via fabric
	- fabric-commands-v0 0.2.3+cf39a74318 via fabric
	- fabric-containers-v0 0.1.13+cf39a74318 via fabric
	- fabric-content-registries-v0 0.4.1+3447790d18 via fabric
	- fabric-crash-report-info-v1 0.1.6+cf39a74318 via fabric
	- fabric-dimensions-v1 2.0.13+cf39a74318 via fabric
	- fabric-entity-events-v1 1.4.1+377137cc18 via fabric
	- fabric-events-interaction-v0 0.4.12+e99fbe1218 via fabric
	- fabric-events-lifecycle-v0 0.2.4+cf39a74318 via fabric
	- fabric-game-rule-api-v1 1.0.8+cf39a74318 via fabric
	- fabric-item-api-v1 1.3.0+6617390918 via fabric
	- fabric-item-groups-v0 0.3.2+cf39a74318 via fabric
	- fabric-key-binding-api-v1 1.0.6+2a2bb57318 via fabric
	- fabric-keybindings-v0 0.2.4+cf39a74318 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.6+0392f3a618 via fabric
	- fabric-loot-tables-v1 1.0.5+cf39a74318 via fabric
	- fabric-mining-level-api-v1 1.0.3+cf39a74318 via fabric
	- fabric-mining-levels-v0 0.1.6+cf39a74318 via fabric
	- fabric-models-v0 0.3.1+cf39a74318 via fabric
	- fabric-networking-api-v1 1.0.14+cf39a74318 via fabric
	- fabric-networking-blockentity-v0 0.2.12+cf39a74318 via fabric
	- fabric-networking-v0 0.3.3+cf39a74318 via fabric
	- fabric-object-builder-api-v1 1.11.0+f907116918 via fabric
	- fabric-object-builders-v0 0.7.7+cf39a74318 via fabric
	- fabric-particles-v1 0.2.5+cf39a74318 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via universal-graves
	- fabric-registry-sync-v0 0.7.13+cf39a74318 via fabric
	- fabric-renderer-api-v1 0.4.5+cf39a74318 via fabric
	- fabric-renderer-indigo 0.4.9+cf39a74318 via fabric
	- fabric-renderer-registries-v1 3.2.6+cf39a74318 via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+cf39a74318 via fabric
	- fabric-rendering-fluids-v1 0.2.1+cf39a74318 via fabric
	- fabric-rendering-v0 1.1.7+cf39a74318 via fabric
	- fabric-rendering-v1 1.10.1+377137cc18 via fabric
	- fabric-resource-loader-v0 0.4.10+f09604ce18 via fabric
	- fabric-screen-api-v1 1.0.5+cf39a74318 via fabric
	- fabric-screen-handler-api-v1 1.1.9+cf39a74318 via fabric
	- fabric-structure-api-v1 1.1.15+cf39a74318 via fabric
	- fabric-tag-extensions-v0 1.2.3+cf39a74318 via fabric
	- fabric-textures-v0 1.0.7+cf39a74318 via fabric
	- fabric-tool-attribute-api-v1 1.3.2+cf39a74318 via fabric
	- fabric-transfer-api-v1 1.5.4+cf39a74318 via fabric
	- fabricloader 0.12.12
	- fasttransferlib 0.5.6 via modern_industrialization
	- ferritecore 3.1.0
	- fiber 0.23.0-2 via collective-fabric
	- fpsreducer 1.24-mc1.17.1
	- full_slabs 3.2.2
	- gbfabrictools 1.3.4+1.17 via clickthrough
	- geckolib3 3.0.30
	- highlighter 1.1.2
	- hologram-api 0.2.1+1.17.1 via universal-graves
	- horizontalpanes 1.1.6
	- horsestatsvanilla 4.1.8
	- hydrogen 0.3
	- iceberg 1.0.27
	- illuminations 1.10.1
	- indium 1.0.1+mc1.17.1
	- inventoryprofilesnext 1.2.2
	- invisframes 2.1.1
	- itemborders 1.1.5
	- jankson 3.0.1+j1.2.0 via libgui
	- java 17
	- kanos_config 0.1.4+1.14.4-1.17.1 via full_slabs
	- kjsextras 1.4.0
	- krypton 0.1.4
	- kubejs 1701.3.10-build.9999
	- lambdynlights 2.1.0+1.17
	- lazydfu 0.1.2
	- legendarytooltips 1.1.5
	- lenientstacksize 1.3.0
	- libgui 4.0.0-beta.4+1.17-rc1 via horsestatsvanilla
	- libninepatch 1.1.0 via libgui
	- libzoomer 0.3.0+1.17.1 via okzoomer
	- lifts 1.4-BETA+1.17
	- lithium 0.7.5
	- loading-timer 1.5
	- lootbeams 2.0.4
	- magna 1.5.5-1.17-pre4 via modern_industrialization
	- malilib 0.10.0-dev.26
	- megane 5.6.1
	- megane-applied-energistics-2 5.6.1+9.0.0-beta.1 via megane
	- megane-base 5.6.1 via megane
	- megane-fabric-transfer 5.6.1+1.5.1-6d0fac4218 via megane
	- megane-fast-transfer-lib 5.6.1+0.5.7 via megane
	- megane-modern-industrialization 5.6.1+0.6.1 via megane
	- megane-reborn-core 5.6.1+5.0.11-beta via megane
	- megane-runtime 5.6.1 via megane
	- megane-team-reborn-energy 5.6.1+2.0.0-beta1 via megane
	- megane-tech-reborn 5.6.1+5.0.11-beta via megane
	- megane-vanilla 5.6.1+1.17.1 via megane
	- microconfig 2.0.1 via lootbeams
	- midnightlib 0.3.0 via blur
	- minecraft 1.17.1
	- minihud 0.19.0-dev.20210707.150016
	- modern_industrialization 0.7.4
	- modmenu 2.0.14
	- okzoomer 5.0.0-beta.3+1.17.1
	- omegamute-fabric 1.9
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_quiltmc_quilt-json5 1.0.0 via okzoomer
	- owo 0.3.2+1.17
	- packet_tweaker 0.2.0+1.17.1 via server_translations_api
	- patchouli 1.17.1-59-FABRIC
	- placeholder-api 1.1.2+1.17.1 via universal-graves
	- playerabilitylib 1.3.0 via modern_industrialization
	- polymer 0.1.8+1.17.1 via universal-graves
	- pride 1.1.0+1.17 via lambdynlights
	- quartzelv 1.2.6+1.17
	- reborncore 5.0.11-beta
	- reeses-sodium-options 1.2.3
	- removehud 1.2.0
	- rhino 1701.1.5-build.71
	- ring_of_attraction 1.1.15
	- roughlyenoughitems 6.3.355
	- roughlyenoughresources 2.2.0
	- satin 1.6.4 via blur
	- searchlight 1.1.3
	- server_translations_api 1.4.8+1.17 via universal-graves
	- sgui 1.0.0-rc5+1.17.1 via universal-graves
	- smoothscrollingeverywhere 3.0.3-unstable
	- sodium 0.3.3+build.8
	- sodium-extra 0.3.6
	- spark 1.6.3
	- spruceui 3.3.0+1.17 via lambdynlights
	- starlight 1.0.0+fabric.73f6d37
	- statement 4.1.3+1.14.4-1.17.1 via full_slabs
	- statement_vanilla_compatibility 1.0.1+1.16.5-1.17 via full_slabs
	- stonecutter_recipe_tags 2.0.0 via consistency_plus
	- team_reborn_energy 2.0.0-beta1 via appliedenergistics2
	- techreborn 5.0.11-beta+local
	- toms_storage 1.1.18
	- trinkets 3.0.4
	- tweakeroo 0.11.0
	- universal-graves 1.1.4+1.17.1
	- valley 2.0.3
	- windowedfullscreen 1.0.0
	- wthit 3.11.2
	- xaerominimap 21.23.0
	- xaeroworldmap 1.19.0
	- xps 0.3.2.r_for_1.17.x_Fabric

**Comment by Darkhax** [comment]
Thank you for reporting this issue, it looks like architectury and this mod are both incompatible with each other. I've already reached out to them and we will hopefully find a solution.

**Comment by Darkhax** [comment]
This should be fixed in the new version.
